### ISSUE TITLE
Style login page(s)

### ISSUE THREAD

**Issue by EmilDickson** [kthfootprint/FootPrint#29]

**Comment by JonatanLindstrom** [comment]
Forgot the extra user data prompt. It's in there now

**Comment by JonatanLindstrom** [comment]
Since overflow:hidden, the full forms etc. doesn't show on a low-height screen.

Suggestion: 
- Disable landscape mode on mobile
- Make inner elements (e.g. form) scrollable and keep div with background to overflow: hidden

(Mostly a note to self, will look into it next thing I do)

**Comment by JonatanLindstrom** [comment]
- Bug with background image showing at bottom fixed as of now on [the branch "loginPrettiness"](https://github.com/kthfootprint/FootPrint/tree/loginPrettiness)
